plugins:
  "issue_comment.created":
    - name: "hello-world-plugin name"
      description: "hello-world-plugin description"
      command: "/hello"
      example: "/hello example"
      skipBotEvents: true
      uses:
        # hello-world-plugin
        - plugin: http://127.0.0.1:9090
          type: github
          with:
            response: world
